### ISSUE TITLE
codecov security breach: regenerate tokens/keys

### ISSUE THREAD

**Issue by klauer** [slac-lcls/networkfox#1]
https://github.com/slac-lcls/networkfox/blob/74f5f76ca03e40d32843c1f46724819da69d726e/.travis.yml#L30

This may apply to you. Recommended to update your secrets/tokens ASAP.

See: https://about.codecov.io/security-update/

**Comment by syamajala** [comment]
I'm not sure if it does? We dont actually use codecov and that is just leftover from the original graphkit. I was looking at travis and I see this when it tries to execute codecov:
```
$ codecov

Skipping a deployment with the pypi provider because this repo's name does not match one specified in .travis.yml's deploy.on.repo: yahoo/graphkit
Skipping a deployment with the pypi provider because this is not on the required runtime
Skipping a deployment with the pypi provider because this is not a tagged commit
```

I guess we should probably just remove it?

**Comment by klauer** [comment]
We (PCDS / pcdshub org) are scrubbing any repositories that even install it, just out of an abundance of caution. 

Feel free to close and move on if you feel that level of cautiousness is unnecessary 😄

**Comment by syamajala** [comment]
I removed codecov and all the old graphkit deploy stuff from the travis.yml. Thanks!
